server:
  port: 8080
  servlet:
    context-path: /fin-control

spring:
  application:
    name: ""
    description: ""
    version: __Local__
    git-hash: __Hash__

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level - %msg%n'
